CREATE DATABASE IF NOT EXISTS cbt_sejarah_pgri11 CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE cbt_sejarah_pgri11;

CREATE TABLE IF NOT EXISTS questions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  bab VARCHAR(50) NOT NULL,
  type ENUM('mcq', 'short_essay', 'essay') NOT NULL DEFAULT 'mcq',
  text TEXT NOT NULL,
  options_json LONGTEXT NULL,
  correct VARCHAR(10) NULL,
  ai_keywords_json LONGTEXT NULL,
  rubric TEXT NULL,
  points DECIMAL(5,2) NOT NULL DEFAULT 2.00,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS exam_sessions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  bab_key VARCHAR(50) UNIQUE NOT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 0,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS exam_tokens (
  id INT AUTO_INCREMENT PRIMARY KEY,
  token_code VARCHAR(20) NOT NULL,
  expires_at DATETIME NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS student_submissions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nisn VARCHAR(30) NOT NULL,
  nama VARCHAR(150) NOT NULL,
  kelas VARCHAR(100) NOT NULL,
  bab_ujian VARCHAR(50) NOT NULL DEFAULT 'ALL',
  nilai_total DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  skor_pg DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  skor_esai DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  benar INT NOT NULL DEFAULT 0,
  salah INT NOT NULL DEFAULT 0,
  pelanggaran INT NOT NULL DEFAULT 0,
  waktu_submit DATETIME DEFAULT CURRENT_TIMESTAMP,
  answers_json LONGTEXT NULL,
  evaluation_json LONGTEXT NULL,
  INDEX idx_nisn (nisn),
  INDEX idx_kelas (kelas)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;